#!/bin/sh

PROXY=$SCR/maven

remove() {
  if [ -e $PROXY ]; then
    rm -v $PROXY
  fi
}

create() {
   touch $PROXY
   echo 'mvn $*' > $PROXY
   chmod 755 $PROXY
}

if [ $# = 1 ]; then
  if [ $1 = 0 ]; then
    remove
  fi
  if [ $1 = 1 ]; then
    create
  fi
fi 
