#!/bin/sh

APP=[xdiff]
ARG1=$1
TMP1=.diff1
ARG2=$2
TMP2=.diff2


if (test -e "$ARG1") then
	if (test -e "$ARG2") then
		if ( test -f "$ARG1" || test -f "$ARG2" ) then
			diff -y --ignore-tab-expansion --ignore-space-change --suppress-common-lines "$ARG1" "$ARG2"
		else
			ls "$ARG1" >> "$TMP1"
			ls "$ARG2" >> "$TMP2"
			diff -y --ignore-tab-expansion --ignore-space-change --suppress-common-lines "$TMP1" "$TMP2"
			rm "$TMP1" "$TMP2"
		fi
	else
		echo "$APP" "$ARG2" does not exist
		echo "$APP" nothing to compare
	fi
else
	echo "$APP" "$ARG1" does not exist
	echo "$APP" nothing to compare
fi
